export const haberdasheryInputs = [
    {
      id: 1,
      name:'photo',
      type:'file',
      accept:'image/*',
      placeholder:"Photo de l'article",
      label:"Photo de l'article",
      errorMessage:'Doit être un fichier de type image',
      required: true,
      info: 'photo',
    },
    {
      id: 2,
      name:'name',
      type:'text',
      placeholder:'ex: Bouton Gem',
      label:"Nom de l'article",
      errorMessage:"Photo de l'article doit comporter entre 2 et 50 caractères, sans caractères spéciaux",
      pattern:"^[\\w\\xc0-\\xff' ']{2,30}$",
      required: true,
      info: 'name',
    },
    {
      id: 3,
      name:'website',
      type:'text',
      placeholder:'ex: www.sudocoud.fr ou Sudocoud',
      label:'Site web /magasin',
      errorMessage:'Ce champ doit comporter entre 2 et 50 caractères',
      // pattern:"^[\\w\\xc0-\\xff' ']{2,30}$",
      // pattern:"((^https?):\/\/[a-z0-9\/:%_+.,#?!@&=-]+)|\w+[\.]*\s*",
      pattern:"^[\\w\\xc0-\\xff' ']{2,30}$|(https?:\/\/)?(?:www\.|(?!www\.))(([a-zA-Z0-9][a-zA-Z0-9-]+[a-zA-Z0-9]|[a-zA-Z0-9]+)\.)+(([a-zA-Z0-9][a-zA-Z0-9-]*[a-zA-Z0-9]|[a-zA-Z0-9]){2,})\/?$",
      required: true,
      info: 'website',

    },
    {
      id: 4,
      name:'haberdashery',
      type:'select',
      placeholder:'type de mercerie',
      label:'Type de mercerie',
      htmlFor: 'haberdasheryType',
      optionsList: [ 'Accessoires broderie', 'Accessoires lingerie','Aiguilles/Epingles/Pinces', 'Biais', 'Boucles/Fermoirs', 'Boutons', 'Boutons pression', 'Ciseaux/Roulettes', 'Colles', 'Cordons/Lacets', 'Crayons', 'Curseurs', 'Elastiques', 'Etiquettes', 'FE à la pièce', 'FE au mètre', 'Fils à bâtir', 'Fils à broder',  'Fils à coudre', 'Fils à crocheter', 'Galons', 'Laine à tricoter', 'Mousquetons', 'Oeillets', 'Ouate/Rembourrage', 'Papier à decalquer', 'Passepoils', 'Poinçoins', 'Règles', 'Repassage', 'Rubans', 'Sangles' ],
      errorMessage:'Sélectionnez un type de mercerie',
      required: true,
      info: 'haberdashery',
    },
    {
      id: 5,
      name:'is_cut',
      type:'select',
      placeholder:'article au mètre',
      label:'Article au mètre ?',
      htmlFor: 'isCutType',
      optionsList: [ 'true', 'false'],
      errorMessage:"Sélectionnez si l'article est à la coupe au mètre ou pas ",
      required: true,
      info: 'is_cut',
    },
    {
      id: 6,
      name:'size',
      type:'number',
      placeholder:'ex: 20',
      label:'Taille / Longueur',
      min: 1,
      max: 10000,
      errorMessage:'Entrez un nombre entre 1 et 10000',
      pattern: '^([1-9]|[1-9][0-9]{1,3}|10000)$',
      required: true,
      info: 'size',
    },
    {
      id: 7,
      name:'unity',
      type:'select',
      placeholder:'unité de mesure',
      label:'Unité de mesure',
      htmlFor: 'unityType',
      optionsList: [ 'mm', 'cm','m' ],
      errorMessage:'Sélectionnez une unité de mesure',
      required: true,
      info: 'unity',
    },
    {
      id: 8,
      name:'quantity',
      type:"number",
      placeholder:'ex: 4',
      label:"Quantité",
      min: 0,
      max: 1000,
      pattern: '^(1000|[1-9][0-9]?)$',
      errorMessage:'entrez un nombre entre 1 et 1000',
      required: true,
      info: 'quantity',
    },
    {
      id: 9,
      name:'color',
      type:'select',
      placeholder:'couleur',
      label:'Couleur',
      htmlFor: 'color',
      optionsList: ['Bleu','Rouge', 'Orange', 'Jaune', 'Vert', 'Rose', 'Violet', 'Marron', 'Gris', 'Noir', 'Blanc', 'Multicolore', 'Beige', 'Or', 'Argent', 'Imprimé', 'Rayures', 'Transparent' ],
      errorMessage:'Sélectionnez une couleur principale',
      required: true,
      info: 'color'
    },
    {
      id: 10,
      name:'precise_color',
      type:'text',
      placeholder:'ex: rose poudré ou ex:#FCDEDC',
      label:'Couleur précise',
      info: 'precise_color',
    },    
    {
      id: 11,
      name:'price',
      type:"number",
      placeholder:'ex: 12.50',
      label:"Prix au mètre ou à l'unité (€)",
      min: 1,
      max: 200,
      pattern:'^[1-9]{1,2}[\,\.]?[0-9]{0,2}$|^[1-9][0]{1}[\,\.]?[0-9]{1,2}$|^1[0-9]{2}[\,\.]?[0-9]{1,2}$|^(200)$',
      errorMessage:'entrez un nombre entre 1 et 200',
      required: true,
      info: 'price',
    },
  ];
